import type { Metadata } from "next";

import "./globals.css";

import Header from "./componets/common/Header";

import Footer from "./componets/common/Footer";



export const metadata: Metadata = {
  title: "Hello Makwana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        
       <Header />



        {children}

        <Footer/>
        
        </body>
    </html>
  );
}
